[package]
name = "wasmer-wasix-js"
version = "0.0.1-alpha.1"
authors = ["Syrus Akbary <syrus@wasmer.io>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
async-trait = "0.1"
base64 = "0.21"
bincode = "1.3.3"
bytes = "1"
console_error_panic_hook = { version = "0.1", optional = true }
derivative = { version = "2" }
futures = "0.3"
http = "0.2"
instant = { version = "0.1", features = ["wasm-bindgen"] }
js-sys = "0.3"
once_cell = "1.18.0"
serde = { version = "1.0.183", features = ["derive"] }
serde-wasm-bindgen = "0.5.0"
tokio = { version = "1", features = ["sync"], default_features = false }
tracing = { version = "0.1", features = ["log", "release_max_level_info"] }
tracing-futures = { version = "0.2" }
tracing-wasm = { version = "0.2" }
url = "2.4.0"
virtual-net = { version = "0.6.0", default-features = false, features = ["remote"] }
virtual-fs = { version = "0.9.0", default-features = false }
wasm-bindgen = { version = "0.2" }
wasm-bindgen-downcast = "0.1"
wasm-bindgen-futures = "0.4"
wasm-bindgen-test = "0.3.37"
wasmer = { version = "4.2", default-features = false, features = ["js", "js-default"] }
wasmer-wasix = { version = "0.14", default-features = false, features = ["js", "js-default"] }
wee_alloc = { version = "0.4", optional = true }
webc = "5.3.0"
shared-buffer = "0.1.3"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

[dependencies.web-sys]
version = "0.3"
features = [
    "BinaryType",
    "Blob",
    "BlobPropertyBag",
    "console",
    "DedicatedWorkerGlobalScope",
    "ErrorEvent",
    "FileReader",
    "Headers",
    "MessageEvent",
    "Navigator",
    "ProgressEvent",
    "ReadableStream",
    "ReadableStreamDefaultController",
    "ReadableByteStreamController",
    "ReadableStreamDefaultReader",
    "Request",
    "RequestInit",
    "RequestMode",
    "Response",
    "Url",
    "WebSocket",
    "Window",
    "Worker",
    "WorkerGlobalScope",
    "WorkerNavigator",
    "WorkerOptions",
    "WorkerType",
    "WritableStream",
    "WritableStreamDefaultController",
    "WritableStreamDefaultWriter",
]

[dev-dependencies]
wasm-bindgen-test = "0.3"

[features]
default = ["console_error_panic_hook", "wee_alloc"]
console_error_panic_hook = ["dep:console_error_panic_hook"]
wee_alloc = ["dep:wee_alloc"]

[profile.dev]
opt-level = 1

[profile.release]
lto = true
opt-level = 'z'

[package.metadata.wasm-pack.profile.release.wasm-bindgen]
debug-js-glue = false
demangle-name-section = false
dwarf-debug-info = false

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["--enable-threads", "--enable-bulk-memory", "-Oz"]

[patch.crates-io]
# virtual-net = { git = "https://github.com/wasmerio/wasmer", branch = "wasmer-js-fixes" }
# virtual-fs = { git = "https://github.com/wasmerio/wasmer", branch = "wasmer-js-fixes" }
# wasmer-wasix = { git = "https://github.com/wasmerio/wasmer", branch = "wasmer-js-fixes" }
# wasmer = { git = "https://github.com/wasmerio/wasmer", branch = "wasmer-js-fixes" }
virtual-net = { path = "../wasmer/lib/virtual-net" }
virtual-fs = { path = "../wasmer/lib/virtual-fs" }
wasmer-wasix = { path = "../wasmer/lib/wasix" }
wasmer = { path = "../wasmer/lib/api" }
