[package]
name = "wasmer-wasi-js"
version = "1.2.0"
authors = ["Syrus Akbary <syrus@wasmer.io>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
js-sys = "0.3.55"
wasm-bindgen = "0.2.73"
# Using the Wasmer 3.0.0 with the revert on stdin/err/out changes
# https://github.com/wasmerio/wasmer/pull/3344. Please use stable version as soon
# as wasmer is released
wasmer = { path = "../wasmer/lib/api", default-features = false, features = ["js", "std"] }
wasmer-wasi = { path = "../wasmer/lib/wasi", default-features = false, features = ["js"] }
wasmer-vfs = { path = "../wasmer/lib/vfs", default-features = false, features = ["mem-fs"] }

[profile.release]
lto = true
opt-level = 'z'
